/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Lenovo
 */
public class Dashboard extends javax.swing.JFrame {
    ResultSet rs;
    Connection con;
    PreparedStatement ps;
    private String sql;
    
    private void checkEmployeeIdPersonal(){
        String empId = txtEmId.getText();
        String query = "SELECT * FROM personal_info WHERE employeeID = ?";
        
        try{
            String url = "jdbc:mysql://127.0.0.1:3306/tism";
            String user = "root";
            String password = "";
            
            con = DriverManager.getConnection(url, user, password);
            
            

            ps = con.prepareStatement(query);
            ps.setString(1, empId);
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                txtFirstName.setText(rs.getString("firstName"));
                txtMiddleName.setText(rs.getString("middleName"));
                txtLastName.setText(rs.getString("lastName"));
                txtEmail.setText(rs.getString("email"));
                txtBirthday.setText(rs.getString("birthday"));
                txtAge.setText(rs.getString("age"));
                txtGender.setText(rs.getString("gender"));
                txtTin.setText(rs.getString("tin"));
                txtAddress.setText(rs.getString("address"));
                txtContactNumber.setText(rs.getString("contact_number"));
                txtPagIbig.setText(rs.getString("pagibig"));
                txtPhilHealth.setText(rs.getString("philhealth"));
                
                
                
                
                btnProcess.setText("Update");
                
            }
            else
            {
                erase();
            }
            
        }catch(SQLException ex)
        {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    
    
    private void erase()
    {
        btnProcess.setText("Add");
                txtFirstName.setText(null);
                txtMiddleName.setText(null);
                txtLastName.setText(null);
                txtEmail.setText(null);
                txtBirthday.setText(null);
                txtAge.setText(null);
                txtGender.setText(null);
                txtTin.setText(null);
                txtAddress.setText(null);
                txtContactNumber.setText(null);
                txtPagIbig.setText(null);
                txtPhilHealth.setText(null);
    }

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        txtEmId.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtEmId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBirthday = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMiddleName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtContactNumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPhilHealth = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPagIbig = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTin = new javax.swing.JTextField();
        btnProcess = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtEmpIdEduc = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtBachelorTitle = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtMasteralTitle = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtDoctorateTitle = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtBachelorMajor = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtBachelorMinor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtBachelorSpecialization = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtMasteralMajor = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtMasteralMinor = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtMasteralSpecialization = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtDoctorateMajor = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtDoctorateMinor = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtDoctorateSpecialization = new javax.swing.JTextField();
        txtBachelorInstitution = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtMasteralInstitution = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtDoctorateInstitution = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtBachelorGraduationDate = new javax.swing.JTextField();
        txtMasteralGraduationDate = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtBachelorGpa = new javax.swing.JTextField();
        txtMasteralGpa = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();

        jTextField2.setText("jTextField2");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 116, 56));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        txtEmId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmIdActionPerformed(evt);
            }
        });
        txtEmId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmIdKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel1.add(txtEmId, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setText("Employee Id");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setText("First Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel1.add(txtFirstName, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setText("Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 50, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 130, 0);
        jPanel1.add(txtAddress, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setText("Age");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 0);
        jPanel1.add(txtAge, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 130, 0);
        jPanel1.add(txtEmail, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setText("Birthday");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 0, 0);
        jPanel1.add(txtBirthday, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel7.setText("Gender");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 50, 0, 0);
        jPanel1.add(jLabel7, gridBagConstraints);

        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 0);
        jPanel1.add(txtGender, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel8.setText("Middle Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPanel1.add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel1.add(txtMiddleName, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel9.setText("Last Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(jLabel9, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel1.add(txtLastName, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Contact Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 0);
        jPanel1.add(jLabel10, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 0, 41);
        jPanel1.add(txtContactNumber, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel11.setText("Philhealth");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 50, 0, 0);
        jPanel1.add(jLabel11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 41);
        jPanel1.add(txtPhilHealth, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel12.setText("Pag-ibig");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 0);
        jPanel1.add(jLabel12, gridBagConstraints);

        txtPagIbig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagIbigActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 41);
        jPanel1.add(txtPagIbig, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel14.setText("Tin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 0);
        jPanel1.add(jLabel14, gridBagConstraints);

        txtTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTinActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 0, 0);
        jPanel1.add(txtTin, gridBagConstraints);

        btnProcess.setText("Add");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 60, 0, 0);
        jPanel1.add(btnProcess, gridBagConstraints);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 30, 0, 0);
        jPanel1.add(jButton1, gridBagConstraints);

        jTabbedPane1.addTab("Personal Information", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 116, 56));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Employee id:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 20));

        txtEmpIdEduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpIdEducActionPerformed(evt);
            }
        });
        txtEmpIdEduc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmpIdEducKeyReleased(evt);
            }
        });
        jPanel2.add(txtEmpIdEduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 260, -1));
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 101, 69, -1));

        jLabel17.setText("Degree Title");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 170, 40));

        txtBachelorTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBachelorTitleActionPerformed(evt);
            }
        });
        jPanel2.add(txtBachelorTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 270, -1));

        jLabel18.setFont(new java.awt.Font("Artifakt Element Black", 0, 11)); // NOI18N
        jLabel18.setText("Hierarchy or Degree");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 210, 20));

        jLabel19.setText("Masteral");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 140, -1));
        jPanel2.add(txtMasteralTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 250, -1));

        jLabel20.setText("Doctorate");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 140, 20));
        jPanel2.add(txtDoctorateTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 240, -1));

        jLabel21.setText("Major");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, -1));
        jPanel2.add(txtBachelorMajor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 270, -1));

        jLabel22.setText("Minor");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 140, -1));

        txtBachelorMinor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBachelorMinorActionPerformed(evt);
            }
        });
        jPanel2.add(txtBachelorMinor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 270, -1));

        jLabel16.setText("Specialization");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 180, -1));
        jPanel2.add(txtBachelorSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 270, -1));

        jLabel23.setText("Major");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 130, -1));
        jPanel2.add(txtMasteralMajor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 250, -1));

        jLabel24.setText("Minor");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 130, -1));
        jPanel2.add(txtMasteralMinor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 250, -1));

        jLabel25.setText("Specialization");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 170, -1));
        jPanel2.add(txtMasteralSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 250, -1));

        jLabel26.setText("Major");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 120, -1));
        jPanel2.add(txtDoctorateMajor, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 240, -1));

        jLabel27.setText("Minor");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 120, -1));
        jPanel2.add(txtDoctorateMinor, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 240, -1));

        jLabel28.setText("Specialization");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 160, -1));
        jPanel2.add(txtDoctorateSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 240, -1));
        jPanel2.add(txtBachelorInstitution, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 270, -1));

        jLabel30.setText("Institution Name");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 180, -1));
        jPanel2.add(txtMasteralInstitution, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 250, -1));

        jLabel31.setText("Institution Name");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 170, -1));
        jPanel2.add(txtDoctorateInstitution, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 240, -1));

        jLabel32.setText("Institution Name");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 190, -1));

        jLabel29.setText("Graduation Date");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 180, -1));

        jLabel33.setText("Graduation Date");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 200, -1));

        jLabel35.setText("Graduation Date");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 190, 20));
        jPanel2.add(txtBachelorGraduationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 270, -1));
        jPanel2.add(txtMasteralGraduationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 250, -1));
        jPanel2.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 240, -1));

        jLabel34.setText("Degree Title");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 160, -1));

        jLabel36.setText("GPA");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 120, -1));

        jLabel37.setText("GPA");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 130, -1));

        jLabel38.setText("GPA");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 120, -1));
        jPanel2.add(txtBachelorGpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 270, -1));
        jPanel2.add(txtMasteralGpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 250, -1));
        jPanel2.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 240, -1));

        jLabel39.setText("Degree Title");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 190, -1));

        jLabel40.setText("Bachelor");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, -1));

        jTabbedPane1.addTab("Educational Background", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 116, 56));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 12, 40, -1));

        jLabel42.setText("Date of Appointment");
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 260, -1));

        jLabel43.setText("Provitionary");
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, -1, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 260, -1));

        jLabel44.setText("Job Position");
        jPanel3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, -1));
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 260, -1));

        jLabel45.setText("School/Institution");
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 260, -1));

        jLabel46.setText("Year of Employment");
        jPanel3.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 260, -1));

        jLabel47.setText("Subject Taught");
        jPanel3.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 260, -1));

        jLabel48.setText("Achievements");
        jPanel3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));
        jPanel3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 260, -1));

        jLabel49.setText("Grade Levels Taught");
        jPanel3.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));
        jPanel3.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 260, -1));

        jLabel50.setText("NC Certificate");
        jPanel3.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));
        jPanel3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 260, -1));

        jLabel51.setText("Retired ");
        jPanel3.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, -1, -1));
        jPanel3.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 260, -1));

        jLabel52.setText("Resign");
        jPanel3.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));
        jPanel3.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 260, -1));

        jLabel53.setText("Profesional Oranization");
        jPanel3.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));
        jPanel3.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 260, -1));

        jTabbedPane1.addTab("Employment History", jPanel3);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(0, 86, 44));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBachelorMinorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBachelorMinorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBachelorMinorActionPerformed

    private void txtBachelorTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBachelorTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBachelorTitleActionPerformed

    private void txtEmpIdEducKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpIdEducKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtEmpIdEducKeyReleased

    private void txtEmpIdEducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpIdEducActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpIdEducActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        try {

            String empId = txtEmId.getText();
            String firstName = txtFirstName.getText();
            String middleName = txtMiddleName.getText();
            String lastName = txtLastName.getText();
            String email = txtEmail.getText();
            String birthday = txtBirthday.getText();
            String age = txtAge.getText();
            String gender = txtGender.getText();
            String tin = txtTin.getText().trim();
            String address = txtAddress.getText();
            String contactNumber = txtContactNumber.getText();
            String pagibig = txtPagIbig.getText();
            String philhealth = txtPhilHealth.getText();

            String url = "jdbc:mysql://127.0.0.1:3306/tism";
            String user = "root";
            String password = "";
            con=DriverManager.getConnection(url, user, password);

            if(btnProcess.getText().equals("Add"))
            {
                sql = "INSERT INTO personal_info(employeeID, firstName, middleName, lastName, email, birthday, age, gender, tin, address, contact_number, pagibig, philhealth) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

                ps = con.prepareStatement(sql);
                ps.setString(1, empId);
                ps.setString(2, firstName);
                ps.setString(3, middleName);
                ps.setString(4, lastName);
                ps.setString(5, email);
                ps.setString(6, birthday);
                ps.setString(7, age);
                ps.setString(8, gender);
                ps.setString(9, tin.isEmpty() ? null: tin);
                ps.setString(10, address);
                ps.setString(11, contactNumber.isEmpty() ? null: contactNumber);
                ps.setString(12, pagibig.isEmpty() ? null: pagibig);
                ps.setString(13, philhealth.isEmpty() ? null: philhealth);

                sql="INSERT INTO educational_background(bachelor_title) VALUES (?)";

                ps.executeUpdate();

                JOptionPane.showMessageDialog(this, "Successfully added to records!1");

            }
            else if(btnProcess.getText().equals("Update"))
            {
                sql = "UPDATE personal_info SET firstName = ?, middleName = ?, lastName = ?, email = ?, birthday = ?, age = ?, gender = ?, tin = ?, address = ?, contact_number = ?, pagibig = ?, philhealth = ?  WHERE employeeID = ?";

                ps = con.prepareStatement(sql);
                ps.setString(1, firstName);
                ps.setString(2, middleName);
                ps.setString(3, lastName);
                ps.setString(4, email);
                ps.setString(5, birthday);
                ps.setString(6, age.isEmpty() ? null:age);
                ps.setString(7, gender.isEmpty() ? null:gender);
                ps.setString(8, tin.isEmpty() ? null : tin);
                ps.setString(9, address.isEmpty() ? null : address);
                ps.setString(10, contactNumber.isEmpty() ? null : contactNumber);
                ps.setString(11, pagibig.isEmpty() ? null : pagibig);
                ps.setString(12, philhealth.isEmpty() ? null : philhealth);
                ps.setString(13, empId);

                ps.executeUpdate();

                erase();

                JOptionPane.showMessageDialog(this, "Record updated!!");

            }

        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnProcessActionPerformed

    private void txtTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTinActionPerformed

    private void txtPagIbigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagIbigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagIbigActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtEmIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmIdKeyReleased
        // TODO add your handling code here:
        checkEmployeeIdPersonal();
    }//GEN-LAST:event_txtEmIdKeyReleased

    private void txtEmIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmIdActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBachelorGpa;
    private javax.swing.JTextField txtBachelorGraduationDate;
    private javax.swing.JTextField txtBachelorInstitution;
    private javax.swing.JTextField txtBachelorMajor;
    private javax.swing.JTextField txtBachelorMinor;
    private javax.swing.JTextField txtBachelorSpecialization;
    private javax.swing.JTextField txtBachelorTitle;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtDoctorateInstitution;
    private javax.swing.JTextField txtDoctorateMajor;
    private javax.swing.JTextField txtDoctorateMinor;
    private javax.swing.JTextField txtDoctorateSpecialization;
    private javax.swing.JTextField txtDoctorateTitle;
    private javax.swing.JTextField txtEmId;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmpIdEduc;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMasteralGpa;
    private javax.swing.JTextField txtMasteralGraduationDate;
    private javax.swing.JTextField txtMasteralInstitution;
    private javax.swing.JTextField txtMasteralMajor;
    private javax.swing.JTextField txtMasteralMinor;
    private javax.swing.JTextField txtMasteralSpecialization;
    private javax.swing.JTextField txtMasteralTitle;
    private javax.swing.JTextField txtMiddleName;
    private javax.swing.JTextField txtPagIbig;
    private javax.swing.JTextField txtPhilHealth;
    private javax.swing.JTextField txtTin;
    // End of variables declaration//GEN-END:variables
}
